apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetworking }}
      hostname: {{ .Values.plex.hostname }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            value: "{{ .Values.plex.timezone }}"
          ports:
            - name: pms
              containerPort: 32400
              protocol: TCP
            {{- if .Values.service.components.DLNA.enabled }}
            - name: pms-dlna-udp
              containerPort: 1900
              protocol: UDP
            - name: pms-dlna-tcp
              containerPort: 32469
              protocol: TCP
            {{- end }}
            {{- if .Values.service.components.homeTheater.enabled }}
            - name: home-theater
              containerPort: 3005
              protocol: TCP
            {{- end }}
            {{- if .Values.service.components.bonjour.enabled }}
            - name: bonjour
              containerPort: 5353
              protocol: UDP
            {{- end }}
            {{- if .Values.service.components.roku.enabled }}
            - name: roku
              containerPort: 8324
              protocol: TCP
            {{- end }}
            {{- if .Values.service.components.gdm.enabled }}
            - name: gdm-1
              containerPort: 32410
              protocol: UDP
            - name: gdm-2
              containerPort: 32412
              protocol: UDP
            - name: gdm-3
              containerPort: 32413
              protocol: UDP
            - name: gdm-4
              containerPort: 32414
              protocol: UDP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /identity
              port: pms
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /identity
              port: pms
            initialDelaySeconds: 15
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}            
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
